---

  - name: MUNIN | Install munin node package
    apt: pkg="{{item}}"
    with_items:
      - "munin-node"
      - "munin-plugins-extra"
    become: yes
    tags:
      - munin


  - name: MUNIN | Enable plugins
    file: path="/etc/munin/plugins/{{item}}" src="/usr/share/munin/plugins/{{item}}" state=link force=yes
    with_items: "{{munin_plugins | default([]) }}"
    become: yes
    tags:
      - munin

  - name: MUNIN | Patch node settings /etc/munin/munin-node.conf
    lineinfile: dest=/etc/munin/munin-node.conf  regexp="{{item.regexp}}" line="{{item.line}}" insertafter="{{item.insertafter | default('EOF')}}"
    with_items: "{{munin_node_properties | default([])}}"
    notify: restart munin
    become: yes
    tags:
      - munin
